-- MySQL Script generated by MySQL Workbench
-- 2018年11月01日 星期四 19时29分54秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- 一个简单的blog的数据库demo

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema my_blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_blog` DEFAULT CHARACTER SET utf8 ;
USE `my_blog` ;

-- -----------------------------------------------------
-- Table `my_blog`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_blog`.`article` (
  `article_id` INT(11) NOT NULL,
  `article_title` VARCHAR(64) NOT NULL,
  `article_author` VARCHAR(32) NULL DEFAULT '卒子',
  `article_title_pic_url` VARCHAR(255) NOT NULL,
  `article_create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  `article_last_update_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`article_id`),
  UNIQUE INDEX `article_id_UNIQUE` (`article_id` ASC));


-- -----------------------------------------------------
-- Table `my_blog`.`article_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_blog`.`article_tag` (
  `article_tag_id`  NOT NULL,
  `article_tag` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`article_tag_id`),
  UNIQUE INDEX `article_tag_id_UNIQUE` (`article_tag_id` ASC));


-- -----------------------------------------------------
-- Table `my_blog`.`article_has_article_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_blog`.`article_has_article_tag` (
  `article_article_id` INT(11) NOT NULL,
  `article_tag_article_tag_id`  NOT NULL,
  PRIMARY KEY (`article_article_id`, `article_tag_article_tag_id`),
  INDEX `fk_article_has_article_tag_article_tag1_idx` (`article_tag_article_tag_id` ASC),
  INDEX `fk_article_has_article_tag_article_idx` (`article_article_id` ASC),
  CONSTRAINT `fk_article_has_article_tag_article`
    FOREIGN KEY (`article_article_id`)
    REFERENCES `my_blog`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_article_tag_article_tag1`
    FOREIGN KEY (`article_tag_article_tag_id`)
    REFERENCES `my_blog`.`article_tag` (`article_tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
